"""taxonomy snapshot

Revision ID: 2128f1bb6fa3
Revises: 
Create Date: 2026-07-17 23:28:00.497519
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2128f1bb6fa3'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('taxonomy_snapshot',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('version_label', sa.String(length=255), nullable=False),
    sa.Column('original_filename', sa.String(length=1024), nullable=False),
    sa.Column('checksum', sa.String(length=64), nullable=False),
    sa.Column('status', sa.Enum('ingesting', 'ready', 'failed', name='snapshot_status'), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_taxonomy_snapshot_checksum'), 'taxonomy_snapshot', ['checksum'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_taxonomy_snapshot_checksum'), table_name='taxonomy_snapshot')
    op.drop_table('taxonomy_snapshot')
    # ### end Alembic commands ###
    # Postgres: drop the enum type left behind by drop_table so a re-upgrade works.
    sa.Enum(name='snapshot_status').drop(op.get_bind(), checkfirst=True)
