"""entity and derived run params

Revision ID: 61a7794b6040
Revises: bd19b16b5b06
Create Date: 2026-07-18 01:58:40.837086
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '61a7794b6040'
down_revision: str | None = 'bd19b16b5b06'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('lei', sa.String(length=20), nullable=False),
    sa.Column('country', sa.String(length=2), nullable=False),
    sa.Column('default_scope', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lei')
    )
    op.add_column('run', sa.Column('entity_id', sa.Integer(), nullable=True))
    # server_default backfills any existing run rows; the ORM default handles new ones.
    op.add_column(
        'run',
        sa.Column(
            'base_currency', sa.String(length=3), nullable=False,
            server_default='EUR',
        ),
    )
    op.add_column(
        'run',
        sa.Column('decimals', sa.Integer(), nullable=False, server_default='-3'),
    )
    op.create_foreign_key('fk_run_entity', 'run', 'entity', ['entity_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_run_entity', 'run', type_='foreignkey')
    op.drop_column('run', 'decimals')
    op.drop_column('run', 'base_currency')
    op.drop_column('run', 'entity_id')
    op.drop_table('entity')
    # ### end Alembic commands ###
