"""workflow_config and run

Revision ID: 7f7eed6fc5af
Revises: 92f7dc097da1
Create Date: 2026-07-18 00:37:22.790083
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f7eed6fc5af'
down_revision: str | None = '92f7dc097da1'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workflow_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('framework_code', sa.String(length=64), nullable=False),
    sa.Column('module_code', sa.String(length=128), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('module_code'),
    sa.UniqueConstraint('name')
    )
    op.create_table('run',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workflow_id', sa.Integer(), nullable=False),
    sa.Column('snapshot_id', sa.Integer(), nullable=False),
    sa.Column('release_id', sa.Integer(), nullable=False),
    sa.Column('reference_date', sa.Date(), nullable=False),
    sa.Column('entity_lei', sa.String(length=64), nullable=False),
    sa.Column('entity_scope', sa.String(length=16), nullable=False),
    sa.Column('country', sa.String(length=2), nullable=False),
    sa.Column('status', sa.Enum('created', 'files_attached', 'running', 'generated', 'failed', name='run_status'), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('failure_details', sa.JSON(), nullable=True),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['snapshot_id'], ['taxonomy_snapshot.id'], ),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflow_config.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_run_snapshot_id'), 'run', ['snapshot_id'], unique=False)
    op.create_index(op.f('ix_run_workflow_id'), 'run', ['workflow_id'], unique=False)
    op.create_foreign_key('fk_fact_run', 'fact', 'run', ['run_id'], ['id'])
    op.create_foreign_key('fk_run_file_run', 'run_file', 'run', ['run_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_run_file_run', 'run_file', type_='foreignkey')
    op.drop_constraint('fk_fact_run', 'fact', type_='foreignkey')
    op.drop_index(op.f('ix_run_workflow_id'), table_name='run')
    op.drop_index(op.f('ix_run_snapshot_id'), table_name='run')
    op.drop_table('run')
    op.drop_table('workflow_config')
    # ### end Alembic commands ###
    # Postgres: drop the enum type left behind by drop_table so a re-upgrade works.
    sa.Enum(name='run_status').drop(op.get_bind(), checkfirst=True)
