"""facts and run_file

Revision ID: 92f7dc097da1
Revises: 2128f1bb6fa3
Create Date: 2026-07-17 23:51:12.414061
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '92f7dc097da1'
down_revision: str | None = '2128f1bb6fa3'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fact',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('template_code', sa.String(length=64), nullable=False),
    sa.Column('row_code', sa.String(length=16), nullable=False),
    sa.Column('column_code', sa.String(length=16), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('entity', sa.String(length=64), nullable=False),
    sa.Column('reference_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fact_run_id'), 'fact', ['run_id'], unique=False)
    op.create_table('run_file',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.Enum('fact_input', 'indicators_params', 'package_output', 'validation_report', name='run_file_role'), nullable=False),
    sa.Column('filename', sa.String(length=1024), nullable=False),
    sa.Column('storage_key', sa.String(length=2048), nullable=False),
    sa.Column('checksum', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_run_file_checksum'), 'run_file', ['checksum'], unique=False)
    op.create_index(op.f('ix_run_file_run_id'), 'run_file', ['run_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_run_file_run_id'), table_name='run_file')
    op.drop_index(op.f('ix_run_file_checksum'), table_name='run_file')
    op.drop_table('run_file')
    op.drop_index(op.f('ix_fact_run_id'), table_name='fact')
    op.drop_table('fact')
    # ### end Alembic commands ###
    # Postgres: drop the enum type left behind by drop_table so a re-upgrade works.
    sa.Enum(name='run_file_role').drop(op.get_bind(), checkfirst=True)
