"""validation findings and fact source

Revision ID: bd19b16b5b06
Revises: f439a10ebb3c
Create Date: 2026-07-18 01:39:00.776009
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bd19b16b5b06'
down_revision: str | None = 'f439a10ebb3c'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('validation_finding',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('severity', sa.Enum('error', 'warning', 'info', name='finding_severity'), nullable=False),
    sa.Column('phase', sa.Enum('pre_generation', 'post_generation', name='validation_phase'), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('file', sa.String(length=1024), nullable=True),
    sa.Column('sheet', sa.String(length=255), nullable=True),
    sa.Column('row', sa.Integer(), nullable=True),
    sa.Column('template_code', sa.String(length=64), nullable=True),
    sa.Column('row_code', sa.String(length=16), nullable=True),
    sa.Column('column_code', sa.String(length=16), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['run.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_validation_finding_code'), 'validation_finding', ['code'], unique=False)
    op.create_index(op.f('ix_validation_finding_run_id'), 'validation_finding', ['run_id'], unique=False)
    op.add_column('fact', sa.Column('source_sheet', sa.String(length=255), nullable=True))
    op.add_column('fact', sa.Column('source_row', sa.Integer(), nullable=True))
    # ### end Alembic commands ###
    # New run status for validation failure (Alembic can't autogenerate this).
    op.execute("ALTER TYPE run_status ADD VALUE IF NOT EXISTS 'failed_validation'")


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fact', 'source_row')
    op.drop_column('fact', 'source_sheet')
    op.drop_index(op.f('ix_validation_finding_run_id'), table_name='validation_finding')
    op.drop_index(op.f('ix_validation_finding_code'), table_name='validation_finding')
    op.drop_table('validation_finding')
    # ### end Alembic commands ###
    # Postgres: drop the enum types left behind by drop_table so a re-upgrade works.
    sa.Enum(name='finding_severity').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='validation_phase').drop(op.get_bind(), checkfirst=True)
